openapi: 3.0.0
info:
  title: Risk Calculation API
  version: 1.0.0
  description: API for calculating risks based on company information and storage tank details.
paths:
  /risk/calculate:
    post:
      summary: Calculates the risk based on the provided request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RiskCalculationRequest'
            example:
              companyInfo:
                latitude: 32.25
                longitude: 118.7833
                name: "德纳（南京）化工有限公司"
              storageTank:
                number: 1
                area: 100
                name: "Tank 1"
                tankLongitude: 118.7833
                tankLatitude: 32.25
                shape: "卧式圆筒罐"
                form: "固定顶罐"
                installationType: 1
                supportHeight: 0.0
                material: "steel"
                shellWeight: 7600
                diameter: 32
                height: 12.44
                volume: 100
                workingAsConstantPressure: true
                storedSubstanceName: "液氨"
                storedSubstanceDensity: 617
                substanceState: 3
                substanceDensity: 0.771
                maxFillingLevel: 0.8
                minFillingLevel: 0.01
      responses:
        '200':
          description: A map containing the calculated risks for different disaster types.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    type: number
              example:
                洪水灾害:
                  情景1: 0.011167
                  情景2: 0.017248
                  情景3: 0.002045
                地震灾害:
                  "烈度：I，风险状态：a": 0.0
                  "烈度：I，风险状态：b": 0.0
                  "烈度：I，风险状态：c": 0.0
                  "烈度：I，风险状态：d": 0.0
                  "烈度：II，风险状态：a": 0.0
                  "烈度：II，风险状态：b": 0.0
                  "烈度：II，风险状态：c": 0.0
                  "烈度：II，风险状态：d": 0.0
                  "烈度：III，风险状态：a": 0.0
                  "烈度：III，风险状态：b": 0.0
                  "烈度：III，风险状态：c": 0.0
                  "烈度：III，风险状态：d": 0.0
                  "烈度：IV，风险状态：a": 0.0
                  "烈度：IV，风险状态：b": 0.0
                  "烈度：IV，风险状态：c": 0.0
                  "烈度：IV，风险状态：d": 0.0
                  "烈度：V，风险状态：a": 0.0
                  "烈度：V，风险状态：b": 0.0
                  "烈度：V，风险状态：c": 0.0
                  "烈度：V，风险状态：d": 0.0
                  "烈度：VI，风险状态：a": 0.0
                  "烈度：VI，风险状态：b": 0.0
                  "烈度：VI，风险状态：c": 0.0
                  "烈度：VI，风险状态：d": 0.0
                  "烈度：VII，风险状态：a": 0.0
                  "烈度：VII，风险状态：b": 0.0
                  "烈度：VII，风险状态：c": 0.0
                  "烈度：VII，风险状态：d": 0.0
                  "烈度：VIII，风险状态：a": 0.0
                  "烈度：VIII，风险状态：b": 0.0
                  "烈度：VIII，风险状态：c": 0.0
                  "烈度：VIII，风险状态：d": 0.0
                  "烈度：IX，风险状态：a": 0.0
                  "烈度：IX，风险状态：b": 0.0
                  "烈度：IX，风险状态：c": 0.0
                  "烈度：IX，风险状态：d": 0.0
                  "烈度：X，风险状态：a": 0.0
                  "烈度：X，风险状态：b": 0.0
                  "烈度：X，风险状态：c": 0.0
                  "烈度：X，风险状态：d": 0.0
                  "烈度：XI，风险状态：a": 0.0
                  "烈度：XI，风险状态：b": 0.0
                  "烈度：XI，风险状态：c": 0.0
                  "烈度：XI，风险状态：d": 0.0
                  "烈度：XII，风险状态：a": 0.0
                  "烈度：XII，风险状态：b": 0.0
                  "烈度：XII，风险状态：c": 0.0
                  "烈度：XII，风险状态：d": 0.0
                台风灾害:
                  高风载荷情境下: 0.03
                  极高风载荷情境下: 0.225
                暴雨灾害:
                  非浮顶罐无需计算: 0.0
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    RiskCalculationRequest:
      type: object
      properties:
        companyInfo:
          $ref: '#/components/schemas/CompanyInfo'
        storageTank:
          $ref: '#/components/schemas/StorageTank'
      required:
        - companyInfo
        - storageTank
    CompanyInfo:
      type: object
      properties:
        address:
          type: string
          description: 通讯地址
        longitude:
          type: number
          format: double
          description: 位置信息 - 经度
        latitude:
          type: number
          format: double
          description: 位置信息 - 纬度
        area:
          type: integer
          description: 占地面积
        industryType:
          type: string
          description: 行业类型
        qValue:
          type: number
          format: double
          description: 企业Q值（环境风险物质数量与其临界量比）
      required:
        - longitude
        - latitude
    StorageTank:
      type: object
      properties:
        number:
          type: integer
          description: 储罐个数
        area:
          type: integer
          description: 储罐区面积
        name:
          type: string
          description: 储罐名称
        tankLongitude:
          type: number
          format: double
          description: 储罐位置 - 经度
        tankLatitude:
          type: number
          format: double
          description: 储罐位置 - 纬度
        shape:
          type: string
          description: 储罐形状
        form:
          type: string
          description: 储罐形式
        floatingRoofDensity:
          type: number
          format: double
          description: 浮顶密度
        floatingRoofThickness:
          type: number
          format: double
          description: 浮顶厚度
        floatingRoofWeight:
          type: number
          format: double
          description: 浮顶重量
        drainagePipeDiameter:
          type: number
          format: double
          description: 排水管道直径
        drainageSystemEfficiency:
          type: number
          format: double
          description: 排水系统效率
        installationType:
          type: integer
          description: 安装形式
        supportHeight:
          type: number
          format: double
          description: 支架高度, 0表示无支架
        material:
          type: string
          description: 储罐材质
        shellWeight:
          type: number
          format: double
          description: 储罐壳体重量
        diameter:
          type: number
          format: double
          description: 直径
        height:
          type: number
          format: double
          description: 高度
        volume:
          type: number
          format: double
          description: 容积
        workingAsConstantPressure:
          type: boolean
          description: 工作压力, true表示为常压
        storedSubstanceName:
          type: string
          description: 储存物质名称
        storedSubstanceDensity:
          type: number
          format: double
          description: 储存物质密度
        substanceState:
          type: integer
          description: 物质状态, 1，2 or 3
        substanceDensity:
          type: number
          format: double
          description: 气体密度
        maxFillingLevel:
          type: number
          format: double
          description: 日常最大填充水平
        minFillingLevel:
          type: number
          format: double
          description: 日常最小填充水平
      required:
        - number
        - area
        - name
        - tankLongitude
        - tankLatitude
        - shape
        - form
        - floatingRoofDensity
        - floatingRoofThickness
        - floatingRoofWeight
        - drainagePipeDiameter
        - drainageSystemEfficiency
        - installationType
        - supportHeight
        - material
        - shellWeight
        - diameter
        - height
        - volume
        - workingAsConstantPressure
        - storedSubstanceName
        - storedSubstanceDensity
        - substanceState
        - substanceDensity
        - maxFillingLevel
        - minFillingLevel